In [1]:
import numpy as np

Numpy is a general purpose array-processing package. It provdes a high performance multidemensional array object and tools for working with thesr arrays are fast

In [2]:
my_list=[1,2,3,4,5]

In [3]:
#converting list into array
arr=np.array(my_list)

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr.shape

(5,)

In [7]:
arr.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [8]:
arr.reshape(5,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [9]:
arr.size

5

# multidimensional array

In [10]:
list_1=[1,2,3,4,5]
list_2=[5,6,2,5,1]
list_3=[2,4,5,6,1]

In [11]:
arr=np.array([list_1,list_2,list_3])

In [16]:
arr

array([[1, 2, 3, 4, 5],
       [5, 6, 2, 5, 1],
       [2, 4, 5, 6, 1]])

In [13]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 5],
       [6, 2, 5],
       [1, 2, 4],
       [5, 6, 1]])

In [15]:
#indexing elements
arr[0][2]

3

In [17]:
arr>1

array([[False,  True,  True,  True,  True],
       [ True,  True,  True,  True, False],
       [ True,  True,  True,  True, False]])

In [18]:
arr[arr>2]

array([3, 4, 5, 5, 6, 5, 4, 5, 6])

In [19]:
#slicing
arr[0:1,:]

array([[1, 2, 3, 4, 5]])

# Bulit in functions

In [20]:
#Arange
np.arange(4)

array([0, 1, 2, 3])

In [21]:
np.arange(2,9,2)

array([2, 4, 6, 8])

In [22]:
np.zeros(2)

array([0., 0.])

In [23]:
np.ones(2)

array([1., 1.])

In [26]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [27]:
arr=np.array([3,5,2,5,2,57,6.4])

In [28]:
arr.sort()

In [29]:
arr

array([ 2. ,  2. ,  3. ,  5. ,  5. ,  6.4, 57. ])

In [32]:
#concatenate
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
np.concatenate((a,b))

array([1, 2, 3, 4, 1, 2, 3, 4])

In [33]:
a.ndim

1

In [34]:
a.size

4